default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
    )

    profile_name = get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.ht.fightweek",
      readonly: false,
    )

    export_options_path = "/tmp/ExportOptions.plist"
    File.write(export_options_path, <<~PLIST)
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
          <key>method</key>
          <string>app-store</string>
          <key>teamID</key>
          <string>QN7Y7DRB28</string>
          <key>signingStyle</key>
          <string>manual</string>
          <key>provisioningProfiles</key>
          <dict>
              <key>com.ht.fightweek</key>
              <string>#{profile_name}</string>
          </dict>
      </dict>
      </plist>
    PLIST

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"],
      xcodeproj: "Runner.xcodeproj",
    )

    sh(
      "unset BUNDLE_GEMFILE BUNDLE_BIN_PATH RUBYOPT GEM_HOME GEM_PATH && " \
      "cd .. && flutter build ipa --release " \
      "--dart-define=ENV=prod " \
      "--dart-define=BASE_URL=#{ENV['PROD_BASE_URL']} " \
      "--export-options-plist=#{export_options_path}",
    )

    upload_to_testflight(
      ipa: "../build/ios/ipa/파이트위크.ipa",
      api_key: api_key,
      skip_waiting_for_build_processing: true,
    )
  end
end
